### ISSUE TITLE
statusText is "error" for any program on http://ide.judge0.com/

### ISSUE THREAD

**Issue by rajmani1995** [judge0/ide#1]
Response for any type of program
```
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}
```
Reason: `data.token` on line 47 should be `data.id` [js/ide.js](https://github.com/judge0/ide/blob/master/js/ide.js)

:heart:  your work !!

**Comment by hermanzdosilovic** [comment]
Hi @rajmani1995,

Thanks for your issue, I am still and currently working on Judge0 API which is behind this Judge0 IDE.

In a few days I will deploy new Judge0 API. For now please visit and try old http://judge0.com

Thanks :smiley:

PS: I will update you in this issue when everything is fixed and ready. Stay tuned.

**Comment by hermanzdosilovic** [comment]
Hey @rajmani1995. Issue resolved. I hope you will enjoy http://ide.judge0.com and other Judge0 services. :smile:
