### ISSUE TITLE
Add numpy (and Tensorflow / other?) support to Python 2 and 3

### ISSUE THREAD

**Issue by kristijanbartol** [judge0/ide#16]
Could be possible to easily integrate additional python images to support some machine learning / deep learning tools with at least CPU support. Will investigate as I found: https://hub.docker.com/r/tensorflow/tensorflow/.

**Comment by kristijanbartol** [comment]
Issue: might be computationally heavy for judge0 to run possible big matrix operations.

**Comment by hermanzdosilovic** [comment]
@kristijanbartol Great feature request!

I will do my research and let you know when and how tensorflow, numpy, scipy and other ML and DL libs will be supported!
