### ISSUE TITLE
Stuck at Running 

### ISSUE THREAD

**Issue by adhavalboy** [judge0/ide#17]
When we submit code and click on submit button it stuck at running phase, may problem with API ?

**Comment by hermanzdosilovic** [comment]
Hi @adhavalboy,

Digital Ocean had network maintenance (BLR1, 2018-05-30 16:30 UTC). After that workers didn't know how to connect to database. Every submission you made is now completed.

Judge0 API is now functional again. Thanks for reporting this issue! :muscle:

BR,
Herman

**Comment by adhavalboy** [comment]
yeah thanks to you also :)

**Comment by adhavalboy** [comment]
Again stuck !!

**Comment by hermanzdosilovic** [comment]
Hey @adhavalboy,

I have added better recovery mechanism to workers when things like this happen. Thanks for your report. Issue is now fixed and should not happen again if there is a network problem with DO droplets.

BR,
Herman

**Comment by adhavalboy** [comment]
many facing this issue!! hope you will solved it permanent.

**Comment by hermanzdosilovic** [comment]
Hi @adhavalboy,

This is solved. What problems are you experiencing? Are you running your own instance of Judge0 API?

**Comment by GalaxyZpj** [comment]
Same issue with me, sometimes it takes forever to receive response from the server.
I am currently building a Django project using Judge0 API using which i can evaluate different testcases for a submission.
sometimes the server just stops responding.

**Comment by hermanzdosilovic** [comment]
I have restarted Judge0 API and problem is solved now.
