### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by adityacoder007** [judge0/ide#19]
Hi,
Great work!

Your API is not working from your IDE is down. could you check?
https://ide.judge0.com/

**Comment by adityacoder007** [comment]
Start working now again. Not sure of the exact issue by I was seeing same submission request was getting called in a loop.

**Comment by aditya999goel** [comment]
Again your IDE is down...

**Comment by aditya999goel** [comment]
https://data.judge0.com/ itself if not loading..

**Comment by hermanzdosilovic** [comment]
Hi @aditya999goel,

API and IDE are now up and running. Sorry for the troubles.
