### ISSUE TITLE
Is it possible to host compiler on own hosts instead of using API?

### ISSUE THREAD

**Issue by malcolmjr96** [judge0/ide#25]
Hi is possible that I can make the code Compile on my site rather than using an API? I find the API works in waves. One point it’s fast next it’s crawling.

**Comment by hermanzdosilovic** [comment]
Hey @malcolmjr96,

yes it is. Take a look at releases page on Judge0 API: https://github.com/judge0/api/releases/tag/v1.1.5.

**Comment by malcolmjr96** [comment]
Thank you!
