### ISSUE TITLE
Request to show compile-time messages too [Nim]

### ISSUE THREAD

**Issue by kaushalmodi** [judge0/ide#27]
Can you also have a window to show the compile time messages too? They are very important when designing macros in Nim.

E.g. I'd like to see what's printed on stdout when just compiling https://nim.ide.judge0.com/?AJNXlTnyLuUARvFY5PvGg_WwCZXt.

Right now, which I hit Run, I see nothing in the output. In that example, I need to look at the messages during compile time as shown below.

![image](https://user-images.githubusercontent.com/3578197/60269812-2b0ca280-98bd-11e9-8bcd-e481c4bd903c.png)

Ref: https://github.com/nim-lang/Nim/issues/11599#issuecomment-506312649

**Comment by hermanzdosilovic** [comment]
Solved and deployed! Enjoy @kaushalmodi :smiley:

**Comment by kaushalmodi** [comment]
Hello, thanks for looking into this.. though, looks like it shows the compilation log only if the run log is empty.

So this case does not work: https://nim.ide.judge0.com/?AMvoP6Fdr0OkFmVQ_ftlrU4YjZU6 (here, I am missing out to see the debug echos for how macros work).

The compilation log is useful to review even when the run log is non-empty.. to see how the macro unrolling happens at compile time.

**Comment by hermanzdosilovic** [comment]
Oh, okay I now understand now better. Do you think that multiple tabs (one for each kind of output) could solve this?

**Comment by kaushalmodi** [comment]
> Do you think that multiple tabs (one for each kind of output) could solve this?

I believe so. I don't have any experience designing UI's, but the user should have an option to look at the compile log and run log separately, I believe.

Probably something like this can be done:

- If compilation fails, highlight the compile log window
- If compilation passes, but run log is empty, highlight the compile log window
- Else highlight the run log window

**Comment by hermanzdosilovic** [comment]
I am working on a new Judge0 IDE that will use [Golden Layout](https://github.com/judge0/api/blob/master/docker-compose.prod.yml#L21-L22) and [Monaco editor](https://github.com/Microsoft/monaco-editor). This feature will be added there. I hope it will be released by the end of the month.

**Comment by hermanzdosilovic** [comment]
Hey @kaushalmodi,

this feature is now available with Judge0 IDE [v2.0.0](https://github.com/judge0/ide/releases/tag/v2.0.0). [Check it out](https://nim.ide.judge0.com/?AMvoP6Fdr0OkFmVQ_ftlrU4YjZU6).

**Comment by kaushalmodi** [comment]
Thanks! Now I can see the compile outputs separately. Nice!
