### ISSUE TITLE
Upgrade 'vlang.ide.judge0.com' to latest release

### ISSUE THREAD

**Issue by gslicer** [judge0/ide#31]
Currently the newest version is 0.1.12 whereas 0.1.22 has been released, therefore please
a) update to the most recent version
OR preferably
b) name it 0.1.x (until 0.2.x will be available) and because of the early development stage where changes happen permanently, please apply "v up" regulary (every day or even as frequent as 1h, it takes just few seconds to update)

(optionally) in case of b) older releases might be dropped

Thanks a lot!

**Comment by hermanzdosilovic** [comment]
Hi @gslicer,

I have created new version of Judge0 API that includes latest V version and automatically updates it with `v up` every hour.

Take a look at https://vlang.ide.judge0.com. Using compiler flag `-v` you can check the V version.

Let me know if you experience any problems or if you have any other feedback on this.

BR,
Herman

**Comment by medvednikov** [comment]
Thanks @hermanzdosilovic

**Comment by medvednikov** [comment]
Just wondering, what do you use for sandboxing @hermanzdosilovic ?

**Comment by hermanzdosilovic** [comment]
Hi @medvednikov,

I am using [isolate](https://github.com/ioi/isolate) for sandboxing.

**Comment by hermanzdosilovic** [comment]
Closing this issue since it has been resolved.
