### ISSUE TITLE
[Feature Request] Have optional setting which combines stdout, stderr and compiler output into a single window

### ISSUE THREAD

**Issue by zangman** [judge0/ide#34]
Having a single output reduces clicks and makes it more similar to a bash terminal.

**Comment by hermanzdosilovic** [comment]
I will add this in the next release. This will require some work on Judge0 API.

Until then, you can now reorder all the panes (drag and drop). Hope that helps for now.

**Comment by hermanzdosilovic** [comment]
Hey @zangman,

this feature is now available. Go to "Settings" and check "Redirect stderr to stdout". :)
