### ISSUE TITLE
getting this error after clicking run button

### ISSUE THREAD

**Issue by wanirauf** [judge0/ide#35]
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}

**Comment by hermanzdosilovic** [comment]
Hi, it seems to that [Judge0 IDE](https://ide.judge0.com/) and[ Judge0 API](https://api.judge0.com/) are [fully operational in the last 48 hours](https://status.judge0.com/). When did you saw this error? What language did you use?

**Comment by zenilharia26** [comment]
For all languages, we are getting the same issue.

**Comment by hermanzdosilovic** [comment]
Can I get the link to the website that uses public instance of Judge0 API where you get this error?

**Comment by darshanc99** [comment]
It's working fine now!
