### ISSUE TITLE
Vlang is not working properly 

### ISSUE THREAD

**Issue by kerolloz** [judge0/ide#40]
![image](https://user-images.githubusercontent.com/36763164/79640022-8d59cb00-818f-11ea-9cfd-b99b6d05fd2f.png)

**Comment by hermanzdosilovic** [comment]
Hi @kerolloz,

Thank you.

I am aware of that, I am trying to fix that for a few months now. This is an API problem that I need to look into more. :)

**Comment by hermanzdosilovic** [comment]
Since I have problems with running V inside a isolate on a Judge0 API side, I have decided to discontinue V for now.
