### ISSUE TITLE
How to deploy in local server

### ISSUE THREAD

**Issue by udaykumar-8329** [judge0/ide#45]
Hi, I would like to use it in local server instead of online, How could i deploy this in local server.

**Comment by hermanzdosilovic** [comment]
I don't have official instructions for this but you should clone or download a project and serve it's content with the HTTP server like Nginx or Apache, or any other web server.

You could for example use Python to serve you the content: `python3 -m http.server 8000`. Detailed instructions are [here](https://stackabuse.com/serving-files-with-pythons-simplehttpserver-module/).
