### ISSUE TITLE
RapidAPI Support

### ISSUE THREAD

**Issue by hiCasper** [judge0/ide#46]
Since June 1st, it can't work with public api, it will be easier to deploy if you can support RapidAPI (like clone the code, fill the auth token and ready-to-use).

**Comment by hermanzdosilovic** [comment]
What you could do locally before deployment is the following:
1. Change the base URL [here](https://github.com/judge0/ide/blob/02d9560be8/js/ide.js#L1) to value `https://judge0.p.rapidapi.com`.
2. Add headers `X-RapidAPI-Host` and `X-RapidAPI-Key` [here](https://github.com/judge0/ide/blob/02d9560be8/js/ide.js#L304-L323), [here](https://github.com/judge0/ide/blob/02d9560be8/js/ide.js#L390-L409) and [here](https://github.com/judge0/ide/blob/02d9560be8/js/ide.js#L440-L452). Value of `X-RapidAPI-Host` header should be `judge0.p.rapidapi.com` and value of `X-RapidAPI-Key` should be your API key that RapidAPI gave you.

I hope this helps.

Herman

**Comment by armornet** [comment]
can you please let me know how to add the code and below which line..

**Comment by hermanzdosilovic** [comment]
Hi @armornet,

1. Clone this repository.
2. Checkout to `rapidapi` branch.
3. Add you API key to [here](https://github.com/judge0/ide/blob/rapidapi/js/ide.js#L5).

Note: You can get your API key here: https://rapidapi.com/hermanzdosilovic/api/judge0
