### ISSUE TITLE
Some thing went wrong when I click Run button

### ISSUE THREAD

**Issue by langonginc** [judge0/ide#48]
Return a checkbox and the information is:

```json
{
    "readyState": 0,
    "status": 0,
    "statusText": "error"
}
```

**Comment by hermanzdosilovic** [comment]
How can I reproduce this on https://ide.judge0.com?

**Comment by Priyajit08** [comment]
for me it says 
{
    "readyState": 4,
    "responseText": "403 Forbidden",
    "status": 403,
    "statusText": "error"
}
when I try running the code. The issue is not happening on https://ide.judge0.com. It's only in my self hosted IDE that this issue is occurring.
In the console it says - 
jquery.min.js:2 POST https://secure.judge0.com/standard/submissions?base64_encoded=true&wait=false 403
