### ISSUE TITLE
Editor themes

### ISSUE THREAD

**Issue by hermanzdosilovic** [judge0/ide#5]
It would be cool if we could change editor theme with using [CodeMirror](https://codemirror.net/demo/theme.html).

User would see dropdown (in navbar) of avaliable themes and when he selects his theme whole interfaces changes in that style.

**Comment by dgarvit** [comment]
I'd like to work upon this!

**Comment by hermanzdosilovic** [comment]
@dgarvit you are welcome! :smile:

**Comment by hermanzdosilovic** [comment]
@dgarvit any progress with this?

**Comment by dgarvit** [comment]
yup. but on doing it, only the side bar seems to change, text area remains white. font color changes too. so, is that okay, or as I am guessing, the text area color should change too?

**Comment by hermanzdosilovic** [comment]
@dgarvit text area color should change too. Try removing [this](https://github.com/judge0/ide/blob/master/css/ide.css#L35) line.

**Comment by dgarvit** [comment]
Removing that line didn't work.
