### ISSUE TITLE
unable to run on local host can you please solve my problem

### ISSUE THREAD

**Issue by PRANEETH-REDDY-23899** [judge0/ide#52]
unable to run the code through localhost 
![Screenshot (247)](https://user-images.githubusercontent.com/50946773/90019766-7c980c80-dccc-11ea-8e26-e12837aff0a6.png)

**Comment by hermanzdosilovic** [comment]
Can this https://github.com/judge0/ide/issues/46#issuecomment-658234842
help you?

**Comment by PRANEETH-REDDY-23899** [comment]
How can i get a rapid API key is it paid or free?

**Comment by bukyapavankumar** [comment]
ya me too previously i was able to run this without generating keys but now it requires it?

**Comment by Nidiots** [comment]
Its working fine in local , just change the url to local server in ide.js

**Comment by kangshihang1998** [comment]
我也遇到了这种情况，我把后端api 的服务器ip地址改成了和前端部署机器同一个网段。 就可以使用了

**Comment by kangshihang1998** [comment]
> 我也遇到了这种情况，我把后端api 的服务器ip地址改成了和前端部署机器同一个网段。就可以使用了

还有一点就是把 ide.js 里的 defaultUrl 地址改成你自己的后端服务器地址
例如：var defaultUrl = localStorageGetItem("api-url") || "http://192.168.96.252:2358";
这个是我本地修改之后的配置
