### ISSUE TITLE
Unable to run "Python for ML" in my local 

### ISSUE THREAD

**Issue by AnubhabMondal** [judge0/ide#57]
![Screenshot (529)](https://user-images.githubusercontent.com/43597328/111570954-e3822480-87cb-11eb-9d09-224b7f1f77ec.png)
Hi Sir,
I cloned judge0/ide/rapidapi branch then add all credentials for judge0 extra CE. But when I run "Python for ML" code it gives me Error 403.
Is there any way to run "Python for ML" locally without using Docker?
Can Somebody please help me on this? @hermanzdosilovic @ron-popov 
Thanks in advance !!

**Comment by AnubhabMondal** [comment]
@hermanzdosilovic @ron-popov Can you please put your valuable comment on that?

**Comment by ron-popov** [comment]
@AnubhabMondal My last commit to this project was more than a year ago, so sadly no, I can't comment on that

**Comment by bholanathbarik9748** [comment]
I have the same problem plz help us @hermanzdosilovic

**Comment by hermanzdosilovic** [comment]
Checkout again with the latest commits and it should work.
