### ISSUE TITLE
Unable to run input() in Python

### ISSUE THREAD

**Issue by adithraghavs** [judge0/ide#58]
I'm unable to run the input() function in Python here. This is my code:
```
x = input('What is your name? ')
print(x)
```

**Comment by hermanzdosilovic** [comment]
Hey @adithraghavs,

I was able to run your code.

![image](https://user-images.githubusercontent.com/7927278/117554387-926a1080-b057-11eb-9c9a-72c759410845.png)

Is there anything that I am missing here?

**Comment by chandansgowda** [comment]
@hermanzdosilovic  Is there any way to run code in interactive mode? Like I want the program to take input while running. Is that possible?

**Comment by hermanzdosilovic** [comment]
@chandansgowda unfortunately no that is not possible. Follow https://github.com/judge0/judge0/issues/273 for the updates on that matter.
