### ISSUE TITLE
IDe not work in localhost

### ISSUE THREAD

**Issue by bholanathbarik9748** [judge0/ide#59]
![Screenshot (240)](https://user-images.githubusercontent.com/71944044/118320970-91832400-b51a-11eb-8e6f-f7619b7d414e.png)
plz help me @hermanzdosilovic

**Comment by hermanzdosilovic** [comment]
Checkout and clone the latest version of Judge0 IDE.

**Comment by bholanathbarik9748** [comment]
yes sir it's work ,Thank you
