### ISSUE TITLE
How do I contact you?

### ISSUE THREAD

**Issue by XtremeDevX** [judge0/ide#63]
Hey Herman,

First off, thank you so much for building judge0, it's an incredible tool and I can't thank you more for open-sourcing it. I scheduled a call with you through the website (there was a link and then I scheduled for basically now, however it doesn't seem like you are available at the moment). Do let me know where and how we can chat! 

Appreciate it, and apologies for creating an issue - for I could not find any other active platform to contact you through!

**Comment by tfjybj** [comment]
> Hey Herman,
> 
> First off, thank you so much for building judge0, it's an incredible tool and I can't thank you more for open-sourcing it. I scheduled a call with you through the website (there was a link and then I scheduled for basically now, however it doesn't seem like you are available at the moment). Do let me know where and how we can chat!
> 
> Appreciate it, and apologies for creating an issue - for I could not find any other active platform to contact you through!

You can have a try. 
https://judge0.com/#contact-us

Good luck.
