### ISSUE TITLE
IDE Not Working

### ISSUE THREAD

**Issue by Aaditya188** [judge0/ide#64]

**Comment by kangshihang1998** [comment]
您好，我也遇到了同样的问题。
我使用了如下两个解决方案，解决了这个问题。可以参考下我的这篇文章，有错误的地方希望给与指正。
https://blog.csdn.net/kangshihang1998/article/details/122865121?spm=1001.2014.3001.5501

**Comment by hermanzdosilovic** [comment]
I have updated version of Monaco editor. It should work now.
