### ISSUE TITLE
Does online ide perform online debugging function? It is breakpoint debugging. Or do you have any recommended open source projects that support breakpoint debugging?

### ISSUE THREAD

**Issue by Tiang-88** [judge0/ide#74]
Does online ide perform online debugging function? It is breakpoint debugging. Or do you have any recommended open source projects that support breakpoint debugging?

**Comment by LucianoTrujillo** [comment]
@hermanzdosilovic @ron-popov updates on this?

**Comment by hermanzdosilovic** [comment]
Hi @LucianoTrujillo, unfortunatelly, Judge0 IDE does not support that.
